plugins {
    id 'eclipse'
    id 'maven-publish'
    id 'net.neoforged.moddev.legacyforge' version '2.0.78'
}

version = "${project.mc_version}-${project.mod_version}"
group = 'com.teamrazor.deep_aether'
archivesBaseName = 'deep_aether'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

legacyForge {
    version = project.mc_version + '-' + project.forge_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }

    accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        client {
            client()
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
            systemProperty 'mixin.env.remapRefMap', 'true'
            systemProperty 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            systemProperty 'forge.enabledGameTestNamespaces', 'deep_aether'
        }
        server {
            server()

            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
            systemProperty 'mixin.env.remapRefMap', 'true'
            systemProperty 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            programArgument '--nogui'
            systemProperty 'forge.enabledGameTestNamespaces', 'deep_aether'
        }
        gameTestServer {
            type = "gameTestServer"
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
            systemProperty 'mixin.env.remapRefMap', 'true'
            systemProperty 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            systemProperty 'forge.enabledGameTestNamespaces', 'deep_aether'
        }

        data {
            data()
            systemProperty 'forge.logging.console.level', 'debug'
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty "mixin.env.remapRefMap", "true"
            systemProperty "mixin.env.refMapRemappingFile", "${projectDir}/build/createSrgToMcp/output.srg"

            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
            environment 'target', 'fmluserdevdata'
        }

        configureEach {
            // Recommended logging data for a userdev environment
            // The markers can be added/remove as needed separated by commas.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            systemProperty 'forge.logging.markers', 'REGISTRIES'

            // Recommended logging level for the console
            // You can set various levels here.
            // Please read: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }
    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven { url = "https://packages.aether-mod.net/The-Aether" }
    maven { url = "https://packages.aether-mod.net/Emissivity" }
    maven { url = "https://packages.aether-mod.net/Treasure-Reforging" }
    maven { url = "https://packages.aether-mod.net/Protect-Your-Moa" }

    maven { url = "https://maven.theillusivec4.top/" }
    maven { url = 'https://maven.minecraftforge.net/' }
    maven {
        name "Modding Legacy Maven"
        url "https://maven.moddinglegacy.com/maven"
    }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
    maven {
        // location of the maven that hosts JEI files since January 2023
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    flatDir {
        dir 'libs'
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}
obfuscation {
    createRemappingConfiguration(configurations.localRuntime)
}

dependencies {
    modImplementation (annotationProcessor("io.github.llamalad7:mixinextras-common:0.3.2"))
    modImplementation (jarJar("io.github.llamalad7:mixinextras-forge:0.3.2"))

    //Dependencies
    modImplementation ("com.aetherteam.aether:aether:${project.aether_version}")
    modImplementation ("com.aetherteam.nitrogen:nitrogen_internals:${project.nitrogen_version}")
    modImplementation ("com.aetherteam.cumulus:cumulus_menus:${project.cumulus_version}")
    modLocalRuntime ("top.theillusivec4.curios:curios-forge:${project.curios_version}")
    modCompileOnly ("top.theillusivec4.curios:curios-forge:${project.curios_version}:api")
    modImplementation ("com.github.glitchfiend:TerraBlender-forge:${project.terrablender_version}")
    modImplementation ("local:aeroblender:1.20.1-1.0.2-rc1-neoforge")
    jarJar ("local:aeroblender:1.20.1-1.0.2-rc1-neoforge")

    //Optional Dependencies
    modCompileOnly ("com.aetherteam.protect-your-moa:aether_protect_your_moa:${project.protect_your_moa_version}")
    modCompileOnly ("com.aetherteam.emissivity:aether_emissivity:${project.emissivity_version}")
    //modCompileOnly ("com.aetherteam.treasure_reforging:aether_treasure_reforging:${project.treasure_reforging_version}")
    modCompileOnly ("curse.maven:aether-lost-content-318602:${project.lost_aether_content_version}")
    modCompileOnly ("com.legacy:structure-gel:${project.structure_gel_version}")
    modCompileOnly ("curse.maven:aether-redux-867237:${project.aether_redux_version}")
    modCompileOnly(("mezz.jei:jei-${mc_version}-common-api:${jei_version}"))
    modCompileOnly(("mezz.jei:jei-${mc_version}-forge-api:${jei_version}"))
    modLocalRuntime(("mezz.jei:jei-${mc_version}-forge:${jei_version}"))
    modCompileOnly ("curse.maven:ancient-aether-886751:${ancient_aether_version}")

    modImplementation ("curse.maven:aether-treasure-reforging-1016302:5759738")
    
    implementation("org.jetbrains:annotations:23.0.0")
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "${mod_id}.mixins.json"
}

dependencies {
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

jar {
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json"
    ])
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : project.mod_name,
                "Specification-Vendor"    : project.mod_authors,
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.jar.archiveVersion,
                "Implementation-Vendor"   : project.mod_authors,
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
    finalizedBy 'reobfJar'

    archiveClassifier = 'no-embeds'
}

mixin {
    config "${project.mod_id}.mixins.json"
    add sourceSets.main, "${project.mod_id}.refmap.json"
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}
processResources {
    exclude '.cache/'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

build {
    dependsOn 'jarJar'
}